### ISSUE TITLE
Having trouble with space jam

### ISSUE THREAD

**Issue by Pushplaybang** [practicalmeteor/meteor-mocha-console-reporter#11]
Hey There

When running this with spacejam I get the following error:

```sh
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console
phantomjs: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
```

I've disabled the Browser-Policy package i was using, as I thought that may have something to do with it, but still no dice.

I'm on OSX running 10.11.6, node v4.2.6, phantom 2.0.0

**Comment by Pushplaybang** [comment]
This is related to browser-policy, by disabling browser policy on localhost, and including it in a local production on package (using the `prodOnly` flag) was the cleanest way to work around this.

**Comment by passingcloud** [comment]
how to do that , provide step by step guide ?
