### ISSUE TITLE
Version 0.2.1 did not finish running with spacejam

### ISSUE THREAD

**Issue by bcbrian** [practicalmeteor/meteor-mocha-console-reporter#6]
You can checkout this repo https://github.com/bcbrian/meteor-app-with-bdd-tdd-ci
When you upgrade to 0.2.1 the tests never finish running. To get it to work I had to roll back to 0.2.0. I will submit PR if I can identify a code problem. I also might just be doing it wrong.

**Comment by jsep** [comment]
Hello @bcbrian I've just release a new version that should solve this issue.

Run this to test it out:

```
meteor add practicalmeteor:mocha@=2.4.5-rc4.1
meteor add practicalmeteor:mocha-console-runner@=0.2.2-rc.1
```

Let me know any progress.

Thanks!

**Comment by jsep** [comment]
The 0.2.2 version should solve this problem

**Comment by bcbrian** [comment]
#7  👍 Sorry it took so long
Fixes the issues.
